language: python
dist: xenial
sudo: required
cache:
- apt
addons:
  apt:
    packages:
    - nginx
    - curl
    - wget
    - ruby
    - ruby-dev
install:
- sudo gem install inspec
- sudo curl -sL -o /tmp/terraform.zip https://releases.hashicorp.com/terraform/0.11.7/terraform_0.11.7_linux_amd64.zip
- sudo unzip -d /usr/local/bin /tmp/terraform.zip
- sudo gem install bundler
- bundle install
script:
- terraform fmt
- terraform init
- kitchen converge
- kitchen verify
- kitchen destroy
env:
  github_token:
    secure: gmkizujhwHHco7fSlYiWxfHvjco5ijHlAso+F2lPqrVjebT33Xj9WwQR7vNuv0Bqef4ynWJYe5zlHr4oQbvdzcoaS0awuYGgN2DLgp9C+lxApqJVxghQwPCno+znCqFL1Gdp2hlvwkE6EMpY/Vxlhr25D/nxW2NUneV8UOlkcfQcJeQeQCaexNDNwUe5iaWTOkDhCmevF6qJD5gW6OIJpDvG34+un9BlRn11lRcSow5xMfZpxH7SnoLjbmSyW8jzA1BbrOHAtH563BZnXAvTS3fLXWsfRKaj4KmSry7RIuH6leJP5WLlflOAO39+Ks2zux+vh55ULqnxnD8tjtSAw2oH5u5peioN4s+CTr/H89e1t1yALwtf3u1XxmoDYzAfzCyM8CfaU4JPVzN0GQlz67vKyjkWwCIw9ybTO96gp0FAKUuO4pkzVS9THisnXyZS+oha0LJDgYhlDWFrSjPD4vSC9I4vJbGNpLporZtYP6iXh4+P+7kiItZ/EuKv+BAVKfIAdb1FUz71u2HRvPoFWodAl2u0x9z6N5vH6ft+72ekIejRShENW1lnzNh97uDYuqUEc9CUVbnoDSB/u4knsZIdtQkD6xTyYn/of6/dqFqOYLg+lYPTgDf4QdrsXYZ0UEWt1Ox2Sj15vdv14l+jHyUvpkysFU+4F5WxP0+zFYc=
