language: python
dist: xenial
sudo: required
cache:
- apt
addons:
  apt:
    packages:
    - nginx
    - curl
    - wget
    - ruby
    - ruby-dev
install:
- sudo gem install inspec
- sudo curl -sL -o /tmp/terraform.zip https://releases.hashicorp.com/terraform/0.11.7/terraform_0.11.7_linux_amd64.zip
- sudo unzip -d /usr/local/bin /tmp/terraform.zip
- sudo gem install bundler
- bundle install
script:
- terraform fmt
- terraform init
- kitchen converge
- kitchen verify
- kitchen destroy
env:
  global:
    secure: RYA14qKMH14GTSYZtbKP7ZN9ZuTseqUOH6jy9r9uePIwMSftmijsb3MBxxoTgiKsBfgqpE3i2cgL9b6YrrhfGBvQX5w7LB2GxR38VffAn/kOM1Ot4Y8+SJ+KnxSX97gX5kFGYGcgZcDC04X7VNLgI7bytoZDvAr1/L3jQFY/3KEM61ECSSqhr4qoEiVk7g8aQbpwdSXNcKgLUmBEW5RL48AhixUc6Y24AFT9mLlgHPsnInEj9WR+byi0gN/cqnZon9w9rOVDyrLVip6kUSTOpaum/vpmuzhnWalTYBgOn7rJpH5ywzg01PoUzaKbGheLEF+HAMI2D1ipgpTaCsTvV+UmT3X7sbJVhmNEX6coSUTgh0O/W7AOB2PHZzAz245k6wor49OjYnZr8+LtSajUuBFCskbGy8vi0A9DYU7m+qfzgH4RRy7qpb9Fs+7lNYCp/hLDpm1maoVtGG2ELRnkkq3SfAWl4ZILG0a4SkFK5oqrPsextqqb5Trz3kXdtp8Y8c7V9gWWNB3PNYTAJFGYETDeK85KrPXyGapSJaeqhIIbJ5MDtyHLAEmrM6Kz9SSGxYlUHUDlgA4p/8632lh/K2ICnO83Pc9mpx2bUVAbmnYBER5LTFXg5ZeHhDkVFG4NH5eku5pf1LxWydohGv8xors4FanH8rJP9J8R54szo8I=
