language: python
dist: xenial
sudo: required
cache:
- apt
addons:
  apt:
    packages:
    - nginx
    - curl
    - wget
    - ruby
    - ruby-dev
install:
- sudo gem install inspec
- sudo curl -sL -o /tmp/terraform.zip https://releases.hashicorp.com/terraform/0.11.7/terraform_0.11.7_linux_amd64.zip
- sudo unzip -d /usr/local/bin /tmp/terraform.zip
- sudo gem install bundler
- bundle install
script:
- terraform fmt
- terraform init
- kitchen converge
- kitchen verify
- kitchen destroy
env:
  global:
    secure: TDHU9W7VekSEbA6GedYyo1xG55hCjJvjQG0c/rbzFNo92g3+HM5HDInt6NwA96s1/vfSZ9RjRsQQhMqwwxZCgkbtPKc91vrimU9Jt5q+DxUaSyaeg63SsDVfwquxL6utAdzCdQ3qLqY/N7exLzepHy4D5ieIS2+UNmmHA5rfgx7FKUdgV95ZYKb/XAhcXpqg6Np3OztI0pPMkZwVkZdyqobYjNijWNy/s8bnsFo9pbfhzn5Exw6fEgEv9GdfUtmY5w1G7TWSmCrvIaUidQGsyPZuyzvZHkVH2+Adk3j3VVIokXqplm6HNHg2jX0OieHWGC4iqmHgspC1dsGvdDgOPCPF2ujr4NUQ3mqQkoF/QRRGMXCGo5CMums67oZXQMYbnD46ArGCO7ZF1yEquZ5yysGkd6o+khPi3OtNGRNNhvlsDjHhs1hWlm779z7rCPMdYQxoRBahrw1E/JQjV9g+izhHcBLEfjSeQuMnSrqImwTvLC4074vOWyY7yDpS0oCGG5GsgQjEwg5B7UurVFN+nv7rQlrG3G78oEQzp66QcRXNZVakPEZx1PjDlnyfo9bmYGDm07jc4dEhjABxOPVlBN5POS2Ca7ANoTTKFoHDyjSRnF36w2WRfxB5MTImUVpkVHJl5+1fxPK96BgRzuGrAkSBMskax2fLJYFax8wwfeE=
